//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod about_texts;
pub mod prelude;
pub mod projects;
pub mod resources;
pub mod skills;
pub mod testimonials;
pub mod timelines;
pub mod users;