//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::about_texts::Entity as AboutTexts;
pub use super::projects::Entity as Projects;
pub use super::resources::Entity as Resources;
pub use super::skills::Entity as Skills;
pub use super::testimonials::Entity as Testimonials;
pub use super::timelines::Entity as Timelines;
pub use super::users::Entity as Users;
